### ISSUE TITLE
Creación de prototipo y guía de estilos

### ISSUE THREAD

**Issue by Reyvaj14** [VanessaSantosPuente/ReservaOrdenadores#7]
> estimación 1

**Descripción**
Creación del prototipo y la guia de estilo a utilizar
- [x] Prototipo
- [x] Guia de estilos

**Comment by DAM119MarioP** [comment]
>estimacion 2023-03-08 0.5

Prototipo y mapa de navegación realizados

**Comment by DAM119MarioP** [comment]
>estimacion 2023-03-08 1

Guia de estilos realizada y subida en formato word como pdf
